
service: serverless-lambda-githubactions

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2
  disableRollback: true

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb


